SELECT USER
FROM DUAL;
--==>> SCOTT

CREATE TABLE TBL_JOBS
( JOBID   VARCHAR2(20)
, JOBNAME VARCHAR2(20)
,CONSTRAINT JOB_ID_PRIMARY PRIMARY KEY(JOBID)
);


CREATE TABLE TBL_USER
( USERID        VARCHAR(20)
, USERNAME VARCHAR2(20)
, USERBIRTH VARCHAR2(20)
, USERJOB VARCHAR2(20)
, CONSTRAINT USERNAME_PRIMARY PRIMARY KEY(USERID)
, CONSTRAINT 
);