SELECT USER
FROM DUAL;
--==>> SCOTT

CREATE TABLE TBL_JOBS
( JOBID   VARCHAR2(20)
, JOBNAME VARCHAR2(20)
,CONSTRAINT JOB_ID_PRIMARY PRIMARY KEY(JOBID)
);

CREATE SEQUENCE JOB_SEQ NOCACHE;

INSERT INTO TBL_JOBS(JOBID, JOBNAME) VALUES(JOB_SEQ.NEXTVAL, 'ÇÐ»ý');
INSERT INTO TBL_JOBS(JOBID, JOBNAME) VALUES(JOB_SEQ.NEXTVAL, 'È¸»ç¿ø');
INSERT INTO TBL_JOBS(JOBID, JOBNAME) VALUES(JOB_SEQ.NEXTVAL, '¹é¼ö');
INSERT INTO TBL_JOBS(JOBID, JOBNAME) VALUES(JOB_SEQ.NEXTVAL, 'ÃëÁØ»ý');

SELECT * FROM TBL_JOBS;

DROP TABLE TBL_USER;

CREATE TABLE TBL_USER
( USERID        VARCHAR(20)
, USERNAME VARCHAR2(20)
, USERBIRTH DATE
, JOBID VARCHAR2(20)
, CONSTRAINT USERNAME_PRIMARY PRIMARY KEY(USERID)
, CONSTRAINT USERJOB_FOREIGN FOREIGN KEY(JOBID)
            REFERENCES TBL_JOBS(JOBID)
);
ALTER SESSION SET NLS_DATE_FORMAT ='YYYY-MM-DD';

CREATE SEQUENCE USER_SEQ NOCACHE;

INSERT INTO TBL_USER(USERID, USERNAME, USERBIRTH, JOBID) VALUES(USER_SEQ.NEXTVAL, 'ÃÖÃ¶³ç', TO_DATE('1993-10-13', 'YYYY-MM-DD'),'4');
INSERT INTO TBL_USER(USERID, USERNAME, USERBIRTH, JOBID) VALUES(USER_SEQ.NEXTVAL, '±èÃ¶³ç', TO_DATE('1993-10-13', 'YYYY-MM-DD'),'2');
INSERT INTO TBL_USER(USERID, USERNAME, USERBIRTH, JOBID) VALUES(USER_SEQ.NEXTVAL, '¹ÚÃ¶³ç', TO_DATE('1993-10-13', 'YYYY-MM-DD'),'1');
INSERT INTO TBL_USER(USERID, USERNAME, USERBIRTH, JOBID) VALUES(USER_SEQ.NEXTVAL, 'ÀÌÃ¶³ç', TO_DATE('1993-10-13', 'YYYY-MM-DD'),'3');

SELECT * FROM TBL_USER;

-- ¡Û ºä ±¸¼º
CREATE OR REPLACE VIEW VIEW_USER
AS
SELECT USERID, USERNAME, MONTHS_BETWEEN(TRUNC(SYSDATE,'YEAR'),
TRUNC(USERBIRTH,'YEAR')) /12 +1 AS USERAGE,
(SELECT JOBNAME FROM TBL_JOBS WHERE JOBID = U.JOBID) AS JOBNAME
FROM TBL_USER U;

SELECT USERID, USERNAME, USERAGE, JOBNAME FROM VIEW_USER
;
SELECT JOBID, JOBNAME FROM TBL_JOBS
;
commit;

SELECT USERID, USERNAME, MONTHS_BETWEEN(TRUNC(SYSDATE,'YEAR'),
TRUNC(USERBIRTH,'YEAR')) /12 +1 AS USERAGE,
(SELECT JOBNAME FROM TBL_JOBS WHERE JOBID = U.JOBID) AS JOBNAME
FROM TBL_USER U;

DELETE FROM TBL_USER WHERE USERID ='3'
;

ROLLBACK;